"""Add profile_image to Student

Revision ID: aaf7b86a2e14
Revises: f9f51e5ae944
Create Date: 2026-07-14 17:35:32.327864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf7b86a2e14'
down_revision: Union[str, Sequence[str], None] = 'f9f51e5ae944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'profile_image')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
