"""add case_study table

Revision ID: b06bcdc4feb1
Revises: a5b255af9528
Create Date: 2026-07-13 17:11:29.814513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06bcdc4feb1'
down_revision: Union[str, Sequence[str], None] = 'a5b255af9528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('youtube_video_id', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_study_display_order'), 'case_study', ['display_order'], unique=False)
    op.create_index(op.f('ix_case_study_id'), 'case_study', ['id'], unique=False)
    op.create_index(op.f('ix_case_study_name'), 'case_study', ['name'], unique=False)
    op.create_index(op.f('ix_case_study_youtube_video_id'), 'case_study', ['youtube_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_study_youtube_video_id'), table_name='case_study')
    op.drop_index(op.f('ix_case_study_name'), table_name='case_study')
    op.drop_index(op.f('ix_case_study_id'), table_name='case_study')
    op.drop_index(op.f('ix_case_study_display_order'), table_name='case_study')
    op.drop_table('case_study')
    # ### end Alembic commands ###
