"""Add profile_image to Admin

Revision ID: f9f51e5ae944
Revises: b06bcdc4feb1
Create Date: 2026-07-14 17:28:13.433118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f51e5ae944'
down_revision: Union[str, Sequence[str], None] = 'b06bcdc4feb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'profile_image')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
